name: CI pipeline
on:
  push:
    branches:
      - main
jobs:
  Build-image:
    runs-on: ubuntu-latest
    env:
      ECR_REPOSITORY: django-api
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      - name: Run Kubernetes tools
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          
          IMAGE_TAG: ${{ github.sha }}
        uses: stefanprodan/kube-tools@v1
        with:
          kubectl: 1.21.0
          kustomize: 4.4.1
          command: |
            cd ./kubernetes/manifests
            kustomize edit set image busybox=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            kustomize build .

      - name: deploy to cluster
        uses: kodermax/kubectl-aws-eks@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        with:
          args: apply -k ./kubernetes/manifests
            